export const POLL_PARTICIPATION_POINTS = 5;
export const POLL_CORRECT_ANSWER_POINTS = 10;

export const MOVIE_LIST_DEFAULT_OFFSET = 0;
export const MOVIE_LIST_DEFAULT_LIMIT = 30;
export const MOVIE_LIST_DEFAULT_SORT = 'DESC';
